### ISSUE TITLE
Pull Riff video stats from all AI Course Cohort 1 activity

### ISSUE THREAD

**Issue by ebporter** [rifflearning/riff-server#10]
We would like to report the following stats at in-person NEXT Capstone Event **on 5/6**. @jordanreedie - this is just a repeat of the story you did a couple weeks ago, but with a fresh backup of the video database. https://drive.google.com/drive/folders/1D23VRx-MIsIzfUb0u5tjgpLjJ5XfsvXZ

**For the dates of the course start (3/1) to present:** 

- Meeting Length
- Meetings by day
- Meetings by hour
- Meetings by week
- Meetings by weekday
- Meetings by month
- Meetings by number of participants

**Story acceptance criteria:**
A shared google drive containing:
- A spreadsheet containing data for the metrics above
- Visual graphics for those metrics

**Comment by adonahue** [comment]
@ebporter - we didn't talk about this about sprint planning, but the timing looks like it might need to be worked on now? If so, I need more information about the dev work involved and the data requirements. Thanks!

**Comment by juliariffgit** [comment]
Ready for Review/QA

**Comment by juliariffgit** [comment]
@ebporter and @juliariffgit to review and close
